name: main 
on: [push]
jobs: 
  Test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: python3 hello.py
  Build:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:       
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with: 
          name: hello 
          path: . 
